"""add foto to vehiculo

Revision ID: 3417c381d5bb
Revises: 6fc3ac4d973a
Create Date: 2025-07-06 01:32:07.727337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3417c381d5bb'
down_revision = '6fc3ac4d973a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
