"""qr logica

Revision ID: 6fa35037cbc7
Revises: 0c5bd98450d7
Create Date: 2025-07-08 12:13:25.618167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa35037cbc7'
down_revision = '0c5bd98450d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_column('qr_url')

    # ### end Alembic commands ###
