"""empty message

Revision ID: 8836bc730419
Revises: 3417c381d5bb
Create Date: 2025-07-07 23:15:57.143651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8836bc730419'
down_revision = '3417c381d5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas_vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('usuario_cliente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('password_cliente', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas_vehiculos', schema=None) as batch_op:
        batch_op.drop_column('password_cliente')
        batch_op.drop_column('usuario_cliente')
        batch_op.drop_column('qr_url')

    # ### end Alembic commands ###
