"""Migración inicial

Revision ID: ad4d3584535a
Revises: 
Create Date: 2025-07-05 01:43:15.639477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4d3584535a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estaciones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('ubicacion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ci', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('numero_crasis', sa.Text(), nullable=False),
    sa.Column('placa', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('cargas_combustible',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vehiculo_id', sa.BigInteger(), nullable=True),
    sa.Column('estacion_id', sa.BigInteger(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cantidad', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios_publicos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.BigInteger(), nullable=True),
    sa.Column('numero_credencial', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas_vehiculos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.BigInteger(), nullable=True),
    sa.Column('vehiculo_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'vehiculo_id')
    )
    op.create_table('vehiculos_institucionales',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vehiculo_id', sa.BigInteger(), nullable=True),
    sa.Column('nombre_institucion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos_institucionales')
    op.drop_table('personas_vehiculos')
    op.drop_table('funcionarios_publicos')
    op.drop_table('cargas_combustible')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('personas')
    op.drop_table('estaciones')
    # ### end Alembic commands ###
